<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
		<script>
			/* 回调的类型
         1 同步回调：
            理解：立即执行，完全执行完了才结束，不会放入回调队列中
            例子：数组遍历相关的回调函数 / promise的executor函数
         2 异步回调：
            理解：不会立即执行，会放入回调队列中将来执行
            例子：定时器回调 / ajax回调 / promise的成功/失败的回调
         
         */
		</script>
	</head>
	<body>
		<script>
			/* 理解JS中的错误(Error)和错误处理  mdn文档
         1 错误的类型
            Error：所有错误的母类型
            ReferenceError：引用的变量不存在
            TypeError：数据类型不正确的错误
            RangeError：数据值不在其所允许的范围内
            SyntaxError：语法错误
         2 错误处理
            捕获错误：try...catch
            拋出错误：throw error
         3 错误对象
            message属性：错误相关信息
            stack属性：函数调用栈记录信息

         */

			// 1. 常见的内置错误

			// ReferenceError：引用的变量不存在
			// console.log(a); // ReferenceError: a is not defined

			// TypeError：数据类型不正确的错误
			// let b = null;
			// console.log(b.xxx); //TypeError: Cannot read properties of null (reading 'xxx')

			// RangeError：数据值不在其所允许的范围内
			// function fn() {
			// 	fn();
			// }
			// fn(); //RangeError: Maximum call stack size exceeded

			// SyntaxError：语法错误
			// const c = ''''; //SyntaxError: Unexpected string
		</script>
		<script>
			//  2. 错误处理
			// 捕获错误：try...catch
			/* 	try {
				let d;
				console.log(d.xxx);
			} catch (error) {
				console.log('error.message:',error.message);
				console.log('error.stack:',error.stack);
			}
         console.log('出错之后'); */

			// 拋出错误：throw new Error()
			function something() {
				if (Date.now() % 2 === 1) {
					console.log('当前时间为奇数，可以执行任务');
				} else {
					//抛出异常，由调用者来处理
					throw new Error('当前时间为偶数，无法执行任务');
				}
			}
			//捕获处理异常
			try {
				something();
			} catch (error) {
				alert(error.message);
			}
		</script>
	</body>
</html>
